- name: Martin Wayhs Arquitetura
  id: mwa
  description: Desenvolvemos projetos arquitetônicos e projeto de interiores.
  image: arquitect.jpg
  icon: home

- name: WS Invest
  id: invest
  description: A <em>WS Invest</em> é a empresa que auxilia na consultoria da compra de imóveis.
  image: invest.jpg
  icon: building

- name: WS Design
  id: design
  description: Temos a nossa própria marca de móveis sob medida. Desenvolvemos um projeto exclusivo para você.
  image: design.jpg
  icon: furniture

- name: Berlim Ambientes
  id: berlim
  description: Descrição da empresa

- name: Ilumion
  id: ilumion
  description: Transformamos os ambientes internos e externos com os efeitos que só a iluminação proporciona. Além do projeto luminotécnico, oferecemos os produtos, e também desenvolvemos luminárias personalizadas.
  image: ilumion.jpg
  icon: lamp
